### ISSUE TITLE
Crash on creative tab menu

### ISSUE THREAD

**Issue by Rozbiynk** [70CentsApple/ChatNotifier#10]
latest log - https://mclo.gs/XZUxNca
crash report - https://mclo.gs/y8IYyZQ
Seems like rendering issue

**Comment by Rozbiynk** [comment]
it happened when i try to see person model (f5 or inventory)

**Comment by 70CentsApple** [comment]
may be related to nick hider ( or as well as bubble chat maybe)
you can turn them off first before it is fixed,
and it will be fixed when i am free

**Comment by Rozbiynk** [comment]
it always was off
