### ISSUE TITLE
Crash on startup, incompatible with "more chat history" mod.

### ISSUE THREAD

**Issue by RainOfPain125** [70CentsApple/ChatNotifier#12]
https://www.curseforge.com/minecraft/mc-mods/more-chat-history

`---- Minecraft Crash Report ---- // Uh... Did I do that? Time: 2023-08-31 07:02:20 Description: Initializing game java.lang.RuntimeException: Mixin transformation of net.minecraft.class_338 failed 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) 	at net.minecraft.class_315.<init>(class_315.java:469) 	at net.minecraft.class_310.<init>(class_310.java:460) 	at net.minecraft.client.main.Main.main(Main.java:211) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at me.deftware.weaver.Main.startGame(Main.java:116) 	at me.deftware.weaver.Main.main(Main.java:100) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.base/java.lang.reflect.Method.invoke(Method.java:568) 	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) 	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) 	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186) 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144) 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74) Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) 	... 20 more Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method morechathistory_changeMaxHistory(I)I in morechathistory.mixins.json:MixinChatHud from mod morechathistory failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap morechathistory-1.19.1-refmap.json 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) 	... 23 more`

**Comment by 70CentsApple** [comment]
We can modify the size of chat history by using Chat Tools, so there is no need to install More Chat History.
**Edit: Also, it seems that you are using 1.19.1? Chat Tools does not even have a version of 1.19.1 .**
