### ISSUE TITLE
Weird "?" on every system message

### ISSUE THREAD

**Issue by rottakore** [70CentsApple/ChatNotifier#13]
![image](https://github.com/70CentsApple/ChatTools/assets/88859658/372a3b86-4bb7-4c3f-aaba-0feefe04ed45)

It's marked with a red square in the image above.
This question mark appears on commands too, like "kill" or "gamemode" or "weather" and others.

It happens even with the "Hide your own nickname" option enabled or disabled.
I have some other mods that change the chat behaviour but even if I only let CHAT TOOLS in the mods folder it keeps happening.

[latest.log](https://github.com/70CentsApple/ChatTools/files/12794513/latest.log)

Log above.
In the line 47546 of the text file, you'll find the "tes" and "test" that I wrote as demonstrated in the print screen.
In the line 47299 of the text file, you'll find the advancement that I demonstrated in the print screen.
My Minecraft language is in Portuguese-Brazil.

**Comment by 70CentsApple** [comment]
Turn off the highlight tweak, or replace the prefix with a character that can be rendered correctly in your font.
![highlight](https://github.com/70CentsApple/ChatTools/assets/63957117/70a57fb2-89d7-4375-83b6-6ae47239134f)
