### ISSUE TITLE
在指定服务器异常

### ISSUE THREAD

**Issue by kndxhz** [70CentsApple/ChatNotifier#14]
不知为何chattools的所有功能好像在ranmc.cc（版本1.20.2，但兼容1.20.1）这个服务器中都失效了
或许是因为插件改了聊天格式的原因？
但也不至于全部失效啊，所有功能都没用了

**Comment by kndxhz** [comment]
![image](https://github.com/70CentsApple/ChatTools/assets/113306265/7c78bcfe-608f-4af7-bd1e-878ad22fb954)
实测纯净客户端也没用，不是模组冲突
![image](https://github.com/70CentsApple/ChatTools/assets/113306265/760d7ebe-6a71-43b9-9fc6-013c4a5dd4ab)
存储的聊天记录和修改聊天记录上限可用

**Comment by 70CentsApple** [comment]
模组还没有在 1.20.2 上面测试过，等我找时间测试一下
此外，建议把.log日志文件、配置文件（在config目录下）上传一下

**Comment by kndxhz** [comment]
[2023-11-11-2.log.gz](https://github.com/70CentsApple/ChatTools/files/13325135/2023-11-11-2.log.gz)
[2023-11-11-3.log.gz](https://github.com/70CentsApple/ChatTools/files/13325137/2023-11-11-3.log.gz)
[2023-11-11-1.log.gz](https://github.com/70CentsApple/ChatTools/files/13325138/2023-11-11-1.log.gz)
[chat_tools.json](https://github.com/70CentsApple/ChatTools/files/13325139/chat_tools.json)
希望能够尽快改进，我认为这是一个很好的国产mod，以至于我是在mcmod的主页刷到的

**Comment by kndxhz** [comment]
[2023-11-11-2.log.gz](https://github.com/70CentsApple/ChatTools/files/13325135/2023-11-11-2.log.gz)
[2023-11-11-3.log.gz](https://github.com/70CentsApple/ChatTools/files/13325137/2023-11-11-3.log.gz)
[2023-11-11-1.log.gz](https://github.com/70CentsApple/ChatTools/files/13325138/2023-11-11-1.log.gz)
[chat_tools.json](https://github.com/70CentsApple/ChatTools/files/13325139/chat_tools.json)
希望能够快速改进，我认为这是一个很好的国产mod，以至于我是在mcmod的主页刷到的

**Comment by 70CentsApple** [comment]
我在你发的`chat_tools.json`里并没有找到你设置过匹配关键词，所以我也推测不出你**预期的效果**是怎样的。
- 如果你想匹配你自己的名字，可以尝试在这里添加：
![image](https://github.com/70CentsApple/ChatTools/assets/63957117/b2a0a10a-979d-4b82-80d9-527ff5613f72)
- 如果你想用 聊天气泡功能，就自定义聊天气泡规则
- 如果你想用 toast弹窗提醒，我注意到你目前的模式是`ADDON`，这个功能需要下载一些附件来使用（`/chattools download`，确保下载过程网络畅通，必要时使用科学上网）；第二种解决方案是换一种可用的弹窗提醒模式

**Comment by kndxhz** [comment]
这个匹配白名单可以不是正则吗，为什么我使用“*”直接就什么都收不到了
我的预期效果是服务器内所有消息都通知我，附件是正常下载的
MD5:E9832AABB5411FE7CE26ED0BBB9DA98E

**Comment by kndxhz** [comment]
![image](https://github.com/70CentsApple/ChatTools/assets/113306265/cc80d7f6-e518-45a1-ac3d-e11671e4f0b4)
![image](https://github.com/70CentsApple/ChatTools/assets/113306265/ac89cd77-a9aa-40ee-a2c0-ca2c43a73988)
此处的聊天注入也没用

**Comment by 70CentsApple** [comment]
抱歉，匹配白名单我没有对星号做特殊判断，你可以使用`.*`（加一个点）代替。
至于这个聊天注入，在它下面有个匹配黑名单选项列表，展开它可以发现里面的默认值对纯数字做了忽略处理（防止输入箱子商店物品数量的时候被错误地注入），所以单独输入一个1是不会被处理的，你可以试试输入别的东西能不能被注入。
_φ( ·▽·*)♪_

**Comment by 70CentsApple** [comment]
此外，做测试的时候也请额外注意这个选项的开关情况：
![image](https://github.com/70CentsApple/ChatTools/assets/63957117/b72a021c-9bfb-4828-b970-5e973cf508d1)

**Comment by kndxhz** [comment]
感谢，问题都解决了(*^▽^*)

**Comment by kndxhz** [comment]
三种方式的toast都存在漏通知的情况，慢慢修吧，不着急

**Comment by kndxhz** [comment]
![image](https://github.com/70CentsApple/ChatTools/assets/113306265/c7836054-24a3-408b-9989-5a201dd11ca2)
有的时候能有的时候又不能
绝大多数时候都不能
