### ISSUE TITLE
无法点击链接

### ISSUE THREAD

**Issue by xianhongtao** [70CentsApple/ChatNotifier#17]
### Bug description

会导致聊天框的链接点击不了，例如玩家发送https://xx.example.com/url,普通minecraft客户端可以点开一个是否要打开链接的界面，使用mod后点击无反应。

### Steps to reproduce

点击聊天框的任意链接

### Expected behavior

像原版minecraft一样显示是否打开链接

### Actual behavior

无反应

### Minecraft version

1.20.4

### Mod version

2.0.0

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by 70CentsApple** [comment]
![img](https://github.com/70CentsApple/ChatTools/assets/63957117/ff597f5f-0a36-44b3-85b6-2ca4fe6013c6)
你是不是把这个打开了

**Comment by xianhongtao** [comment]
没开哦

**Comment by 70CentsApple** [comment]
我开了个纯净没有装任何 mod 的 1.20.4 单人世界测试了一下，貌似**原版就不能**直接点击打开链接
![img](https://github.com/70CentsApple/ChatTools/assets/63957117/a607cd93-eb68-444d-99de-2e28de3764ea)

**Comment by xianhongtao** [comment]
貌似服务器可以，部分非.com域名好像也不可以

**Comment by xianhongtao** [comment]
印象很清楚，之前玩hypixel就可以直接点开hypixel的官网

**Comment by kitUIN** [comment]
在Forge1.16.5中,Forge有实现识别url的功能,你可能是被这个影响了
原版中应该是没有的
