### ISSUE TITLE
Multiple new versions of Chat Tools may cause game freezes on specific launchers, but they will not crash. However, you may need to wait 2-15 minutes before opening the game.

### ISSUE THREAD

**Issue by Momeyuka** [70CentsApple/ChatNotifier#19]
### Bug description

I initially attempted to replace Chat Patch with it because it has a high execution efficiency and non-invasive mod suitable for chat plugin servers. However, when using Modrinth to launch MC, this mod always causes the game to fail to start, usually requiring waiting 2-15 minutes for a crash before trying again. I tried disabling all other mod and enabling it alone, but the problem still persists. Therefore, I believe there are issues that need to be addressed.

### Steps to reproduce

1. Using Modrinth and separately installing the Chat Tools MOD
2. Tried with the latest version of Fabric and with both 1.20.4/1.20.6
3. The game freezes within five seconds of starting and the CPU usage in Task Manager is 0.

### Relevant logs

[2024-05-19-7.log](https://github.com/70CentsApple/ChatTools/files/15366218/2024-05-19-7.log)
[2024-05-19-6.log](https://github.com/70CentsApple/ChatTools/files/15366231/2024-05-19-6.log)

### Minecraft version

1.20.4/1.20.6

### Mod version

2.0.0/2.1.0/2.1.1

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by 70CentsApple** [comment]
其实，从您发的这两份日志文件中看不出什么异常，没有您在群里发的错误，相比之下，我更关心这部分的日志：
![20240519075126](https://github.com/70CentsApple/ChatTools/assets/63957117/b078aff8-deba-44c0-aa49-f682507ea454)

**Comment by Momeyuka** [comment]
> 其实，从您发的这两份日志文件中看不出什么异常，没有您在群里发的错误，相比之下，我更关心这部分的日志： ![20240519075126](https://private-user-images.githubusercontent.com/63957117/331837504-b078aff8-deba-44c0-aa49-f682507ea454.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMDExMDEsIm5iZiI6MTcxNjEwMDgwMSwicGF0aCI6Ii82Mzk1NzExNy8zMzE4Mzc1MDQtYjA3OGFmZjgtZGViYS00NGMwLWFhNDktZjY4MjUwN2VhNDU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDA2NDAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1YmZmMzg1M2E1NTMyMzg1ZGU0MGEzZDhkMTYzYTNhYjhiOWI0NmFhMWZiNWQyMTQ4NjBkODgzYjdlNmNkMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j96P6DTxnBtMNFWvESnlG4izseynaNvDGLjALbO4t2E)


[2024-05-19-1.log](https://github.com/70CentsApple/ChatTools/files/15368344/2024-05-19-1.log)

**Comment by Momeyuka** [comment]
> 其实，从您发的这两份日志文件中看不出什么异常，没有您在群里发的错误，相比之下，我更关心这部分的日志： ![20240519075126](https://private-user-images.githubusercontent.com/63957117/331837504-b078aff8-deba-44c0-aa49-f682507ea454.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMDExMDEsIm5iZiI6MTcxNjEwMDgwMSwicGF0aCI6Ii82Mzk1NzExNy8zMzE4Mzc1MDQtYjA3OGFmZjgtZGViYS00NGMwLWFhNDktZjY4MjUwN2VhNDU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDA2NDAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1YmZmMzg1M2E1NTMyMzg1ZGU0MGEzZDhkMTYzYTNhYjhiOWI0NmFhMWZiNWQyMTQ4NjBkODgzYjdlNmNkMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j96P6DTxnBtMNFWvESnlG4izseynaNvDGLjALbO4t2E)

在筛查后，我才发现是这个模组存在问题，导致我无法正常启动游戏。最终选择了禁用它。
经过测试，我发现只有CurseForge启动器和Modrinth启动器存在问题，只要安装它就无法启动游戏，完全假死，而其他启动器如PCL则没有任何问题。
所以，我打算在新版本的Chat Tools能够在Modrinth启动器中正常启动之前不再安装。
因为我在制作模组包时，这个问题确实给我带来了很大的困扰。

**Comment by 70CentsApple** [comment]
网络问题 下载资源超时了 可以看看您的网络环境支不支持流畅访问[这个网址](https://70centsapple.top/download/chat_tools/download.php?icon.ico)
至于我这边的话 我可以考虑把下载文件单独拉一个线程出来防止阻塞游戏主线程

**Comment by Momeyuka** [comment]
> 网络问题 下载资源超时了 可以看看您的网络环境支不支持流畅访问[这个网址](https://70centsapple.top/download/chat_tools/download.php?icon.ico) 至于我这边的话 我可以考虑把下载文件单独拉一个线程出来防止阻塞游戏主线程

支持

**Comment by 70CentsApple** [comment]
打算等更新内容多一点再发新版本号，所以如果急的话可以先到这里拿工件：https://github.com/70CentsApple/ChatTools/actions/runs/9234315689

**Comment by 70CentsApple** [comment]
想确认一下这个问题现在还存在吗？因为我个人不太好测试这个bug有没有被修复 @Momeyuka
