### ISSUE TITLE
Restore Messages not recovering messages between game restarts

### ISSUE THREAD

**Issue by jawaulk** [70CentsApple/ChatNotifier#22]
### Bug description

When closing minecraft and reopening it the chat history is not restored even though I do have that feature turned on.
If I log out of a game and log back in without closing minecraft the chat is recovered but not when restarting the game itself.

### Steps to reproduce

1. log into a minecraft world and type something into chat
2.  close minecraft and reopen it
3.  log back into same minecraft world and chat is not restored

### Expected behavior

chat to be restored after closing and reopening minecraft

### Actual behavior

chat is not restored after closing and reopening minecraft

### Minecraft version

1.21

### Mod version

2.2.0

### Other information

does restore chat if you log out and back in without closing minecraft but close minecraft and chat history is gone. even when "enable restore messages" is set to yes

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by 70CentsApple** [comment]
I am sorry, but it seems to be working as intended.

**Comment by jawaulk** [comment]
oh i must of misunderstood what restore chat history is supposed to do. would think it does what other mods do that restore chat history and restore the history after restarting the game. not just after logging out and back into the game without restarting. Is there something wrong with my setup or is this actually how it is supposed to work with your mod?

**Comment by 70CentsApple** [comment]
> Is there something wrong with my setup or is this actually how it is supposed to work with your mod?

There is nothing wrong with your setup, and it is supposed to function just like that.
