### ISSUE TITLE
not a bug but a help guide

### ISSUE THREAD

**Issue by DaZoZElMoz** [70CentsApple/ChatNotifier#42]
### Bug description

i want to make it when someone in chat says welcome so do i how do i do that

### Steps to reproduce

i want to make it when someone in chat says welcome so do i how do i do that

### Minecraft version

1.20.4

### Mod version

latest

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by AlphaLeoli** [comment]
do u wanna say thanks every time someone says welcome or say welcome every time someone joins or what 😭

**Comment by DaZoZElMoz** [comment]
i say welcome when someone says welcome its weird ik but its something for the server

**Comment by 70CentsApple** [comment]
![img](https://github.com/user-attachments/assets/b68a0f22-5158-41c3-8fbc-65de65d3abe7)
Do you mean something like this?

**Comment by DaZoZElMoz** [comment]
> ![img](https://github.com/user-attachments/assets/b68a0f22-5158-41c3-8fbc-65de65d3abe7)
> Do you mean something like this?

Yes this is what I want thanks the [Ww] means if they say in small or capital it will repeat right

**Comment by 70CentsApple** [comment]
> the [Ww] means if they say in small or capital it will repeat right

correct

**Comment by AlphaLeoli** [comment]
does (?i) work to make it case insensitive?

**Comment by 70CentsApple** [comment]
> does (?i) work to make it case insensitive?

idk but you can try

**Comment by DaZoZElMoz** [comment]
i did it 
![image](https://github.com/user-attachments/assets/5c24eb4d-952d-4bae-ab82-cd7fef507ca3)
 but its not working like people say welcome and i dont say anything

**Comment by 70CentsApple** [comment]
@DaZoZElMoz 
Two problems:
1. The server address is not even matched. You should do it like ".*\.berrysmp\.net" or "play\.berrysmp\.net" or "play.berrysmp.net" or something (cases matter). Tip: when the server address is matched, the color should be green but not orange.
2. It will only respond to literal `Welcome` or `welcome`, so if you want to match texts just **including** these, use `.*[Ww]elcome.*`

**Comment by DaZoZElMoz** [comment]
thanks one more thing if like for example 10 people say welcome how do i make it say once only or is that not a feature

**Comment by 70CentsApple** [comment]
> thanks one more thing if like for example 10 people say welcome how do i make it say once only or is that not a feature

not a feature, *at least for now*.
