### ISSUE TITLE
Search Character Limit

### ISSUE THREAD

**Issue by AlphaLeoli** [70CentsApple/ChatNotifier#43]
### Bug description

"how are you doing that one thing" is the max amount of characters you can put in. This breaks a lot of complicated regex u wanna do.
![image](https://github.com/user-attachments/assets/09c9d880-542c-4f4a-aa8a-08a1075b119b)

### Steps to reproduce

1. open the chat search
2. spam it with characters
3. it will not keep going

### Minecraft version

1.20.4

### Mod version

2.3.0

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by 70CentsApple** [comment]
Download the artifacts here: https://github.com/70CentsApple/ChatTools/actions/runs/9932365279
