### ISSUE TITLE
Send Timestamps After New Line

### ISSUE THREAD

**Issue by AlphaLeoli** [70CentsApple/ChatNotifier#45]
### Motivation

It looks ugly
![image](https://github.com/user-attachments/assets/39c0b7dd-2934-4774-bb31-037ad87c115a)

and it looks fake
![image](https://github.com/user-attachments/assets/13279fd0-5702-49b1-8c95-da284f60b2e3)
(i sent both those e4c4 messages with the next command)

### Description

Option to resend the timestamp after a new line

**Comment by 70CentsApple** [comment]
> ### Motivation
> It looks ugly 

As is mentioned in #39 , to split those message into lines and deal with them seperately is unnessasary for me.

> and it looks fake !(i sent both those e4c4 messages with the next command)

Already explained. And dude, this is a debug command. It's better to keep this message fresh and raw.
