### ISSUE TITLE
Remove Chat Character Limit

### ISSUE THREAD

**Issue by AlphaLeoli** [70CentsApple/ChatNotifier#46]
### Motivation

I can't send long commands and it's annoying

### Description

remove the chat character limit
for commands, just let you send them
for messages, have an option to send them separately

**Comment by 70CentsApple** [comment]
If it is the new `/chattools send_to_client` command, it should NOT have length limits.

> for commands, just let you send them

The most probable result is this text will be refused by the server.

> for messages, have an option to send them separately

Might lead to spamming, so no.

**Comment by AlphaLeoli** [comment]
> If it is the new `/chattools send_to_client` command, it should NOT have length limits.

it has a length limit

**Comment by 70CentsApple** [comment]
> > If it is the new `/chattools send_to_client` command, it should NOT have length limits.
> 
> it has a length limit

Oh sorry, but Responder doesn't, you can try it for now.

**Comment by AlphaLeoli** [comment]
> Might lead to spamming, so no.

You mean like if you do a super super large piece of text?
