### ISSUE TITLE
Lag when chat filter filter

### ISSUE THREAD

**Issue by AlphaLeoli** [70CentsApple/ChatNotifier#47]
### Bug description

Whenever the chat filter filters out a message, my game lags. It just drops like the next frame or two and it's frozen for a tiny split second (but very annoying)

### Steps to reproduce

make a filter and make ur message get filtered

### Minecraft version

1.20.4

### Mod version

2.3.0

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by 70CentsApple** [comment]
These optimization might lead to errors like `ListOutOfBound` or messing up with message sequence order.

Please give me feedback in this issues thread. ❤️

**Comment by 70CentsApple** [comment]
I am going to revert these changes, as it breaks multi locks in my Minecraft client.
Breaking multi locks is a critical error and it causes crashes. So, I am sorry for my revert.

**Comment by AlphaLeoli** [comment]
is there no way to make it not lag then?
