### ISSUE TITLE
Responder

### ISSUE THREAD

**Issue by ChiefMadCat** [70CentsApple/ChatNotifier#48]
Hi, I am new to this mod and on a server when a new player joins there is a message saying "» Gracz [nick] jest tu nowy! /powitanie"
I would like the mod to say "siema [nick]"
I have no idea how to set it up, I would be grateful if you help me 

(I am typing here bc I couldn't find any other way of contacting you)

**Comment by 70CentsApple** [comment]
pattern: `.*Gracz (?<nickname>.*) jest tu nowy!.*`
message: `siema {nickname}`
