### ISSUE TITLE
与Viafabricplus存在兼容性问题

### ISSUE THREAD

**Issue by xianhongtao** [70CentsApple/ChatNotifier#49]
### Bug 描述

进入本地存档时游戏崩溃

### 重现步骤

使用同时包含Viafabricplus和ChatTools的游戏启动任意本地存档

### 预期行为

不崩

### 实际行为

崩了

### 相关日志

[2024-07-20-1.log.gz](https://github.com/user-attachments/files/16319168/2024-07-20-1.log.gz)
本人自建网盘:https://fb.xaero.top/share/xWHA9DWL

### Minecraft 版本

1.21

### Mod 版本

2.3.1

### 其他信息

来自文心一言的诊断：
这段日志来自一个Minecraft（我的世界）客户端，使用了Fabric模组加载器以及多个模组（如viafabricplus和chattools）。日志中包含了信息、警告和错误级别的消息，下面是对这些消息的详细解读：

警告消息：
@ModifyConstant conflict警告表明存在常量修改冲突。具体来说，viafabricplus模组和chattools模组都试图修改聊天消息的最大长度，但由于它们的优先级相同（都是1000），Fabric无法决定哪个修改应该被应用。这通常不会导致游戏崩溃，但可能会影响到某些功能（如聊天消息的长度限制）。
错误消息：
java.lang.ExceptionInInitializerError是一个严重的错误，通常发生在静态初始化块中抛出异常时。这个错误没有具体的异常原因（null），但它可能是由类加载过程中的问题或其他静态初始化代码中的错误引起的。
堆栈跟踪显示错误发生在Minecraft的某个内部类中（class_8674），这通常意味着问题可能与Minecraft的核心代码或与之交互的模组代码有关。
解决建议：

检查模组兼容性：由于存在@ModifyConstant冲突，建议检查viafabricplus和chattools模组的兼容性，并查看是否有更新版本解决了这个问题。
查看模组文档和社区：访问这些模组的官方文档或社区论坛，看看是否有其他玩家报告了类似的问题，并查找可能的解决方案。
禁用或卸载模组：如果问题持续存在，尝试禁用或卸载引起冲突的模组，看看是否能解决问题。
检查Java和Minecraft版本：确保你的Java和Minecraft版本与模组兼容。
查看完整的错误日志：如果可能的话，查看完整的错误日志，可能会提供更多关于错误原因的线索。
这些步骤应该能帮助你诊断并解决这个错误。如果问题仍然无法解决，可能需要更深入地调查或寻求来自模组开发者的帮助。

### 检查列表

- [X] 我已经确认问题在最新版本的 Mod 中仍然存在。
- [X] 我已经搜索过现有问题，确认这不是重复的。

**Comment by 70CentsApple** [comment]
如果你等不及新版本号，你可以到这里底部下载工件：https://github.com/70CentsApple/ChatTools/actions/runs/10019311189

**Comment by xianhongtao** [comment]
没事不急
（真的好快啊，才发issue就好了）
发自我的 iPhone

在 2024年7月20日，下午5:57，70CentsApple ***@***.***> 写道：

﻿

如果你等不及新版本号，你可以到这里底部下载工件：https://github.com/70CentsApple/ChatTools/actions/runs/10019311189
