### ISSUE TITLE
Send a "wb" message whenever someone joins

### ISSUE THREAD

**Issue by kicekkic** [70CentsApple/ChatNotifier#50]
### Bug description

I have tried so many different combinations, I don't know anymore, so this is not a bug report but rather asking for something because Im desperate now. Sorry for taking your time :/

### Steps to reproduce

Essentially when someone joins then there is a message "username joined the game", how do I auto respond with message "wb"?

### Minecraft version

1.20.6

### Mod version

2.3.1

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by AlphaLeoli** [comment]
for the pattern do `(?<player>[a-zA-Z0-9_]{3,16}) joined the game` and the response you can put `wb` or `wb {player}` for it to say wb and then their username

**Comment by 70CentsApple** [comment]
Same as above. If it works, then congrats; we can simply close this issue!

**Comment by kicekkic** [comment]
> for the pattern do `(?<player>[a-zA-Z0-9_]{3,16}) joined the game` and the response you can put `wb` or `wb {player}` for it to say wb and then their username

Is that for all usernames? doesnt work

**Comment by kicekkic** [comment]
update: I had to do /chattools on and it fixed the issue :)
