### ISSUE TITLE
Network packet error every time a filtered word matches

### ISSUE THREAD

**Issue by syshotdev** [70CentsApple/ChatNotifier#51]
### Bug description

When a message in chat contains a filtered word (Described in Mod menu -> Chat Tools -> Chat Filter -> Rules) it instantly boots you out of the game and displays "Network Protocol Error".
![image](https://github.com/user-attachments/assets/440e11a8-9d06-476d-a675-c79cbcc0a2fe)

### Steps to reproduce

1. Be on linux (I'm pretty sure this is a linux-specific bug, doesn't matter the distrobution I think)
2. Add all of the required mods (Chat Tools, Fabric API, Cloth Config, Mod Menu for config)
3. Add a rule in (Mod menu -> Chat Tools -> Chat Filter -> Rules), "cat" for example, enable chat filter
4. Join a server and type "cat" in chat
5. Error

### Expected behavior

It either removes the message (As in, it looks like the chat has not moved) or it makes the message blank.

### Actual behavior

I get kicked with a network protocol error

### Relevant logs

https://pastebin.com/ZpRNBz1Z

### Minecraft version

1.21

### Mod version

2.3.1

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by 70CentsApple** [comment]
please try [this action build](https://github.com/70CentsApple/ChatTools/actions/runs/10080384084) and tell me whether it works.
