### ISSUE TITLE
Prefix + Suffix

### ISSUE THREAD

**Issue by AlphaLeoli** [70CentsApple/ChatNotifier#53]
### Motivation

In some servers, you only want to have a prefix in chat. For example, if you're constantly messaging someone then you wanna have it.

### Description

Allow you to add (on a per server basis) a custom prefix and suffix that is automatically appended on to your messages

**Comment by 70CentsApple** [comment]
Do you mean Chat Formatter? We already have that

**Comment by AlphaLeoli** [comment]
oh i see
