### ISSUE TITLE
最大聊天数量可以支持数值输入吗，滑块操作不准确

### ISSUE THREAD

**Issue by MNWZ211** [70CentsApple/ChatNotifier#54]
### 动机

标题

### 描述

标题

**Comment by 70CentsApple** [comment]
可以编辑配置文件 `/chattools config opengui` ，然后重启游戏

**Comment by MNWZ211** [comment]
> 可以编辑配置文件 `/chattools config opengui` ，然后重启游戏

OK，感谢提醒
