### ISSUE TITLE
event preview

### ISSUE THREAD

**Issue by africanoogabooga** [70CentsApple/ChatNotifier#57]
### Bug description

after i enabled it, it does not disable even if set to No

### Steps to reproduce

1. join online server
2. enable event preview
3. works as intented
4. tries to disable/ disable in mod menu settings but stays enabled even if set to off
5. deleted and reinstalled mod
6. deleted the chattools folder in %appdata% and reinstalled nothing

### Expected behavior

disable when set to No

### Actual behavior

event preview stays on even when set to no

### Minecraft version

1.20.1

### Mod version

2.3.4

### Other information

issue occures when im playing online multiplayer where i normally play

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by 70CentsApple** [comment]
I'm going to check this out a few days later, sorry for the delay

**Comment by africanoogabooga** [comment]
that is okay lol its not a big issue just a little annoying lol so no rush, appreciate

> I'm going to check this out a few days later, sorry for the delay

**Comment by africanoogabooga** [comment]
hi @70CentsApple sorry do i reinstall the mod for the problem to be fixed?

**Comment by africanoogabooga** [comment]
nevermind saw the update from an hour ago and downloaded and installed and works perfectly
