### ISSUE TITLE
Custom Join Message Doesn't Work in Singleplayer

### ISSUE THREAD

**Issue by AlphaLeoli** [70CentsApple/ChatNotifier#58]
### Bug description

The custom join message doesn't do anything in singleplayer, even if I put `*` as the regex. Maybe it could check the world name so you could put custom world names as the regex as well as just put * if u want it to do it on all singleplayer worlds.

### Steps to reproduce

1. Make a custom join message with `*` as the regex
2. Join a singleplayer world

### Minecraft version

1.21.1

### Mod version

2.3.4

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by AlphaLeoli** [comment]
also idk if this should be a suggestion or a bug

**Comment by 70CentsApple** [comment]
It's a suggestion, as it is working as designed.

But I could add an option to toggle whether it should work on single player.
