### ISSUE TITLE
My responder doesn't work (completely)

### ISSUE THREAD

**Issue by rolnight** [70CentsApple/ChatNotifier#60]
### Bug description

I've been trying this and that, but I can't get a working responder. I have spent hours of time on this, please help.
I enter a word that should be responded to, but no response comes. Probably it doesn't see the word I'm writing to it at all. Maybe I'm just stupid, I really hope so. I will be able to trigger a command in response to a specific word in a message, right? If anyone can help me, I will worship you.

(And yes, I've tried different versions of the mod and had different players write chat messages. The only thing is that I did not change the game version 1.20.1)

P.s. - ok... I checked with other versions of the game. Same thing. 

![image](https://github.com/user-attachments/assets/ffd00501-dc40-4bf4-b563-778ac0acc1b2)
![image](https://github.com/user-attachments/assets/54864b91-31f7-42eb-af3e-fbf45520ef97)
![image](https://github.com/user-attachments/assets/990733ce-2ab2-49a3-a852-7ca04fb40c36)
![image](https://github.com/user-attachments/assets/44026e9a-8e2e-4f3a-a27e-8bc407258697)

### Steps to reproduce

1. create responder
2. provoke him in the chat room

### Expected behavior

outputting a message to chat or commands

### Relevant logs

[latest.log](https://github.com/user-attachments/files/17972127/latest.log)

### Minecraft version

1.20,1

### Mod version

any

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by 70CentsApple** [comment]
I have been busy recently, perhaps I will check this out someday.

**Comment by 70CentsApple** [comment]
I see. This is because the message Minecraft received has a bracket inserted in front, like `<name> message`. When you deal with your RegEx patterns, you should consider that.

A probably easy solution is to add a `.*` in front of the pattern. If you know how to write a RegEx pattern, you can even go further.

**Comment by rolnight** [comment]
> I see. This is because the message Minecraft received has a bracket inserted in front, like `<name> message`. When you deal with your RegEx patterns, you should consider that.
> 
> A probably easy solution is to add a `.*` in front of the pattern. If you know how to write a RegEx pattern, you can even go further.

I made it, thank you very much! But... It doesn't work with letters, only with numbers. What could that be?

**Comment by 70CentsApple** [comment]
So this is not a Chat Tools problem but a RegEx pattern issue. Perhaps you can learn to write a RegEx pattern by yourself or use something like a certain LLM to help you with that.

I'm so sorry that I'm literally not available these days.

**Comment by rolnight** [comment]
> So this is not a Chat Tools problem but a RegEx pattern issue. Perhaps you can learn to write a RegEx pattern by yourself or use something like a certain LLM to help you with that.
> 
> I'm so sorry that I'm literally not available these days.

Yo. I did it, turns out my build had a chat translation mod and his messages were prioritized for RegEx. Anyway... I got it done, thanks a lot for your help and for your mod ❤.
