### ISSUE TITLE
Tweakermore compatibles

### ISSUE THREAD

**Issue by Rozbiynk** [70CentsApple/ChatNotifier#8]
It crash when i try to load game with it
https://mclo.gs/n8HuBEs

**Comment by 70CentsApple** [comment]
Could you please offer a zip file of all your mods? This helps me to quickly locate the problem from among your numerous mods. As it seems to have nothing to do with Tweakeroo and both two are working fine for me.

**Comment by Rozbiynk** [comment]
oh seems it doesnt tweakeroo itself but tweakermore (https://modrinth.com/mod/tweakermore)

**Comment by 70CentsApple** [comment]
Check out the latest release v1.2.7, if the fix works then we can close this issue.

**Comment by Rozbiynk** [comment]
yes, it work's, that you a lot!
