### ISSUE TITLE
[Suggestion] add functions from chat patches

### ISSUE THREAD

**Issue by Rozbiynk** [70CentsApple/ChatNotifier#9]
Add customize to timestap. For example color, way to disable seconds. 
Compact chat integration. It need ignore timestaps
![изображение](https://github.com/70CentsApple/ChatTools/assets/95433246/4a8442ab-02f2-4a37-9ff8-d73d49bf455b)
Add restoring messages from previous session (ideas were taken from https://modrinth.com/mod/chatpatches, because it doesnt have 1.20 version)

**Comment by Rozbiynk** [comment]
and i cant get how does toast notification works. Im try both methods, but it like no one worked for me. But Im try it with server console
![изображение](https://github.com/70CentsApple/ChatTools/assets/95433246/b4fb7c14-fa3b-464c-8611-62ce3234c790)
Maybe i doing something wrong?

**Comment by 70CentsApple** [comment]
> 

The implementation of this feature uses a lot of tricks, and on some platforms or in some cases they are not supported, so if it fails this is a normal phenomenon.
Also, a known bug is that it will only be triggered by messages tagged with server messages, the rest just try to trigger but fail.

**Comment by 70CentsApple** [comment]
- Timestamp customization: available in v1.2.8
- Compact Chat Integration: See https://github.com/caoimhebyrne/compact-chat/issues/23
- Restoring messages: available in v1.2.8

as for the toast notification, it will toast only if the message **should** be alerted (matched the whitelist).

**Comment by Rozbiynk** [comment]
hm, is there way to remove this part? not only my, but other's people too
![изображение](https://github.com/70CentsApple/ChatTools/assets/95433246/45707c61-3fc9-499d-9762-f93126b275b5)

**Comment by Rozbiynk** [comment]
or this happens only when message marked as system?

**Comment by 70CentsApple** [comment]
> hm, is there way to remove this part? not only my, but other's people too ![изображение](https://user-images.githubusercontent.com/95433246/250298723-45707c61-3fc9-499d-9762-f93126b275b5.png)

Chat Tools v1.3.1 offers a way to activate bubble chat more freely.
You can do so by adding the rule `.* (?<name>.*): (?<message>.*)` _(I don't know if this works well because I don't know the style of the messages in your session. If it doesn't, you can modify it yourself)_
![example](https://github.com/70CentsApple/ChatTools/assets/63957117/1f635801-6abb-49ac-ae0b-895c2bf58aab)

**Comment by Rozbiynk** [comment]
thank you, try it now

**Comment by Rozbiynk** [comment]
thank for you great work! is there work to remove "Restored message" message?

**Comment by 70CentsApple** [comment]
> thank for you great work! is there work to remove "Restored message" message?

Done in v1.3.2

**Comment by Rozbiynk** [comment]
okay, thank

**Comment by 70CentsApple** [comment]
> Add customize to timestap. For example color, way to disable seconds. Compact chat integration. It need ignore timestaps ![изображение](https://user-images.githubusercontent.com/95433246/248278455-4a8442ab-02f2-4a37-9ff8-d73d49bf455b.png) Add restoring messages from previous session (ideas were taken from https://modrinth.com/mod/chatpatches, because it doesnt have 1.20 version)

Hey in case you don't know, Compact Chat now has a new version 2.0.2 that supports timestamps
